version: "3.8"
services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
     - '8002:3000'
    volumes:
      - ./custom.ini:/etc/grafana/grafana.ini